[package]
name = "bevy_editor_cam"
version = "0.3.1"
edition = "2021"
description = "A camera controller for editors and CAD."
license = "MIT OR Apache-2.0"
keywords = ["controller", "camera", "bevy", "CAD"]
repository = "https://github.com/aevyrie/bevy_editor_cam"
documentation = "https://docs.rs/crate/bevy_editor_cam/latest"
exclude = ["assets/"]

[features]
default = ["extension_anchor_indicator", "extension_independent_skybox"]
extension_anchor_indicator = ["bevy_gizmos"]
extension_independent_skybox = ["bevy_asset", "bevy_core_pipeline"]

[dependencies]
bevy_app = "0.15.0-dev"
bevy_color = "0.15.0-dev"
bevy_derive = "0.15.0-dev"
bevy_ecs = "0.15.0-dev"
bevy_input = "0.15.0-dev"
bevy_log = "0.15.0-dev"
bevy_math = "0.15.0-dev"
bevy_reflect = "0.15.0-dev"
bevy_render = "0.15.0-dev"
bevy_time = "0.15.0-dev"
bevy_transform = "0.15.0-dev"
bevy_utils = "0.15.0-dev"
bevy_window = "0.15.0-dev"
# Optional
bevy_asset = { version = "0.15.0-dev", optional = true }
bevy_core_pipeline = { version = "0.15.0-dev", optional = true }
bevy_gizmos = { version = "0.15.0-dev", optional = true }
# 3rd party
bevy_picking_core = "0.20.0"

[dev-dependencies]
bevy = { version = "0.15.0-dev", default-features = false, features = [
    "bevy_gizmos",
    "bevy_gltf",
    "bevy_scene",
    "bevy_text",
    "bevy_ui",
    "bevy_winit",
    "default_font",
    "multi_threaded",
    "jpeg",
    "ktx2",
    "tonemapping_luts",
    "x11",
    "zstd",
] }
bevy_mod_picking = { version = "0.20.0", default-features = false, features = [
    # "backend_raycast",
] }
# big_space = "0.7.0"
rand = "0.8"

[patch.crates-io]
bevy_app = { path = "../bevy/crates/bevy_app" }
bevy_color = { path = "../bevy/crates/bevy_color" }
bevy_derive = { path = "../bevy/crates/bevy_derive" }
bevy_ecs = { path = "../bevy/crates/bevy_ecs" }
bevy_input = { path = "../bevy/crates/bevy_input" }
bevy_log = { path = "../bevy/crates/bevy_log" }
bevy_math = { path = "../bevy/crates/bevy_math" }
bevy_reflect = { path = "../bevy/crates/bevy_reflect" }
bevy_render = { path = "../bevy/crates/bevy_render" }
bevy_time = { path = "../bevy/crates/bevy_time" }
bevy_transform = { path = "../bevy/crates/bevy_transform" }
bevy_utils = { path = "../bevy/crates/bevy_utils" }
bevy_window = { path = "../bevy/crates/bevy_window" }
# Optional
bevy_asset = { path = "../bevy/crates/bevy_asset" }
bevy_core_pipeline = { path = "../bevy/crates/bevy_core_pipeline" }
bevy_gizmos = { path = "../bevy/crates/bevy_gizmos" }
# Dev
bevy = { path = "../bevy" }
# Upstream update needed
bevy_picking_core = { path = "../bevy_mod_picking/crates/bevy_picking_core" }
bevy_mod_picking = { path = "../bevy_mod_picking" }
# transitive dependencies
bevy_hierarchy = { path = "../bevy/crates/bevy_hierarchy" }
bevy_core = { path = "../bevy/crates/bevy_core" }
