[package]
name = "bevy_editor_cam"
version = "0.1.6"
edition = "2021"
description = "A camera controller for editors and CAD."
license = "MIT OR Apache-2.0"
keywords = ["controller", "camera", "bevy", "CAD"]
repository = "https://github.com/aevyrie/bevy_editor_cam"
documentation = "https://docs.rs/crate/bevy_editor_cam/latest"
exclude = ["assets/"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.12.1", default-features = false, features = [
    "bevy_render",
    "bevy_gizmos",
    "bevy_asset",
    "bevy_core_pipeline",
] }
bevy_picking_core = "0.17"

[dev-dependencies]
bevy = { version = "0.12", features = ["jpeg"] }
bevy_mod_picking = { version = "0.17", default-features = false, features = [
    "backend_raycast",
] }

big_space = "0.4"
rand = "0.8"
